import pip
# pip.main(['install', 'wikipedia'])
# pip.main(['install', 'speechRecognition'])
# pip.main(['install', 'bs4'])
# pip.main(['install', 'pynput'])
# pip.main(['install', 'datetime'])
# pip.main(['install', 'pyautogui'])
# pip.main(['install', 'plyer']) # Notification
# pip.main(['install', 'pygame']) # DJ
# pip.main(['install', 'speedtest'])
# pip.main(['install', 'pywhatkit'])
# pip.main(['install', 'webbrowser'])
# pip.main(['install', 'os'])
# pip.main(['install', 'wolframalpha'])
# pip.main(['install', 'googletrans'])
# pip.main(['install', 'gtts'])
# pip.main(['install', 'playsound']) # till python 3.5.0
# pip.main(['install', 'fnmatch'])
# pip.main(['install', 'json'])
# pip.main(['install', 'matplotlib'])
# pip.main(['install', 'pyuac'])
# pip.main(['install', 'ctypes'])
# pip.main(['install', 'sys'])
# pip.main(['install', 'PIL'])
# pip.main(['install', 'tkinter'])
# pip.main(['install', 'pynput'])
# pip.main(['install', 'time'])
# pip.main(['install', 'PIL'])
# pip.main(['install', 'PIL'])
# pip.main(['install', 'PIL'])